#!/bin/bash

git config --global user.name "bfrasholb"

git config --global user.email "13065@holbertonstudents.com"

git config --global credential.helper 'cache --timeout=7200'

git clone https://github.com/bfrasholb/holbertonschool-shell.git